language: node_js
node_js: v12
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.4.x
  - npm install -g lighthouse
  - npm install -g lighthouse-plugin-field-performance
script:
  - export LHCI_BUILD_CONTEXT__CURRENT_HASH=$(head -n 4096 /dev/urandom | openssl sha1 | sed 's/(stdin)=//g' | fold -w 8 | head -n 1)
  - export LHCI_BUILD_CONTEXT__COMMIT_TIME=$(date +%Y-%m-%dT%H:%M:%S%z)
  - export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=master
  - export LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="Periodic run"
  - export LHCI_BUILD_CONTEXT__AUTHOR="No one <noreply@memezilla.com>"
  - export LHCI_BUILD_CONTEXT__AVATAR_URL="https://picsum.photos/id/870/200/200"
  - lhci autorun --upload.token="$LHCI_UPLOAD__TOKEN" # run lighthouse CI
env:
  global:
    - secure: "OIZ/H+HozNIj8A5UXRALVuGdL8RqPgwm4LYpr1SvBAemd4nD49nOpEBqxA3fSNVz1nXXgNVc2hC1mqf/O9ylW+uSDKgwHQrqpxgtytXTGiyFTBrFIMrtN7E2G/O1adqghlzIxpSigvJ4sG8UrufOo6wzKF5hSGWwmjMWTe8pFoR4IpTzbSsATArfLM9JVYXwkkQ33Kh1h80dHTyf4U63ETm2g1T6vsH5FykDWg1xQIKIRynwtqr4zffwzeXYjQbdSYb9oSSLReWN+VpqRSTjQhBnQRPYpnvoWdAIaCsa5MXWq5Ux0EvoksZAt9tUBqHLDDMgLvKPBno0yZkpb3coY4WsM+42saQrJrvMMgwAAZOW/3IXKwz3wNZtkO5HcX7nCApplOIgQW7eoZwqL0JCNqlRzvx46pr+RZQMcjo1cW6s5xCabOfmCaf40O3NUBQfRCMCgAv9NZ8TNKfvGZ5sRqWp/KG0ptCHiUottS6K/42RSlIMS3/zlku/n5zuYmsKJW6wyNkaM5JCx9PeQNeOAlE+M2tKMsqOWQFk9UHVlm7+5rI0MkhYRQeeYF2k4Txrx16PJ/p+AMbQrf7RSKZaBcbu4k7FhVxW/SwcSmTr0hnhzyPfQVfWizt6Jmsygvxv7mTcjetYFy8FyP7RNQn2HiOhbRaBvFwY+GvCekCvqKc="
